## server configuration
server:
  port: 9060
spring:
  application:
    name: search
  shutdown:
    enable: true
  profiles:
    active: svt
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
      - myCache
    caches:
      myCache:
        ttl: 600 # TTL in seconds (adjust as needed)
data service:
  openapi:
    dev-url: http://localhost:9060
management:
  endpoints:
    web:
      exposure:
        include: "*"
theatres:
  publisher:
    topic: theatre



---



## Dev Profile
spring:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9090/mem/test
    username: sa
    initialization-mode: always
   # initialize: true
   # platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---

## SVT Profile
spring:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  config:
    activate:
      on-profile: svt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbp_search
    username: root
    password: password

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

