## server configuration
server:
  port: 9090
spring:
  application:
    name: onboard
  security: ## OAuth2 resource server configuration
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  shutdown:
    enable: true
  profiles:
    active: svt
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
      - myCache
    caches:
      myCache:
        ttl: 600 # TTL in seconds (adjust as needed)
data service:
  openapi:
    dev-url: http://localhost:9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
shows:
  seats:
    exchange: seatsInventory
    exchange.queue: seatsInventoryQueue
theatres:
  exchange:
      name: theatre_exchange
      queue: theatre_exchange_queue
mbp:
  onboard:
    API_KEY: TestAPIKey
logging:
  level:
    com:
      mbp: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
---



## Dev Profile
spring:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
   # url: jdbc:h2:tcp://localhost/~/test
    username: sa
    initialization-mode: always
   # initialize: true
   # platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---

## SVT Profile
spring:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  config:
    activate:
      on-profile: svt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbp_onboard
    username: root
    password: password
    initialization-mode: always
    data: data.sql
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
